### ISSUE TITLE
Homebridge thinks that older version is a new version

### ISSUE THREAD

**Issue by arnthorsnaer** [bwp91/homebridge-ewelink-sonoff#12]
**What issue do you have?**
I noticed that Homebridge is prompting me to update the plugin. The current version is 2.5.9 but according to Homebridge there is a newer one available. I'm not sure how Homebridge determines the order of releases but something appears to be off here.

**Which version of the package are you using?**
2.5.9

**Please paste any relevant logs below**
See screenshot https://imgur.com/WAcqeQ7

**Comment by bwp91** [comment]
Hiya,
Nope nothing off here.
The current version was 2.5.9 but today I have released 2.8.5 a newer version.
The apparent random jump in version numbers is always to match up with the beta version of the plugin which receives a more incremental updates than this package.

**Comment by arnthorsnaer** [comment]
Well this is embarrasing. Nothing off here indeed.
