### ISSUE TITLE
Device takes very long time to update status

### ISSUE THREAD

**Issue by Fannangir** [bwp91/homebridge-ewelink-sonoff#16]
**What issue do you have? Please be as thorough and explicit as possible.**

...After upgrading to the last few releases, devices have a very bad response.
It does change its state immediately when turned on/off, but Home application is spinning the update status wheel with no success obtaining the state of the device, have to wait very long time until the device is updated (if at all).
Sometimes clicking on the device a few times does acquire the correct sate of the device.

**Which version of the package are you using?**
Latest, started happening in the latest few updates, was working perfect about a week ago (before the 3~4 updates pushed in the last few days).
...

**Please paste any relevant logs below. It helps if you can turn `debug` and `debugReqRes` in the package settings for more thorough logging.**

...

**Comment by bwp91** [comment]
Hi,
Please could I get you to install/try the beta version of this package? It's a separate package called homebridge-ewelink-beta.
Easiest way is to uninstall homebridge-ewelink-sonoff (but keeping the plugin config as Homebridge asks) and then installing homebridge-ewelink-beta, and then restart Homebridge.

I have just released an update to the beta package, rolling back changes I have made to the connections.

I would be interested to see if you found it worked as before - please let me know how you get on.

Thanks for bringing this to my attention!
Ben

**Comment by Fannangir** [comment]
Hi Ben,
Thank you very much for such fast support.
I have replaced the plugins as you have asked.
Works perfect with the beta, no issues.
I can see the device updated in the application and in home app (works both ways, use two ewelink users).

Thanks,
Arie.

**Comment by bwp91** [comment]
Ah fab.
The changes I made were to wait for an “ok” response from ewelink upon sending an update for a device.
It appears that this response could sometimes take a few seconds, obviously those seconds can seem a lot longer when waiting for a device to respond.
So i have reversed these changes in the beta, and it almost becomes a trade off between fastness and reliability.
I’ll publish an update to this main package (ewelink-sonoff) later today so you can switch back to this package as you wish once the update is out.

**Comment by bwp91** [comment]
Also, if by “two users” you mean a main account for ewelink app and a “shared” account for Homebridge, this used to be my setup. But recently I have noticed you seem to be able to use one account for both without being logged out the other, so now I use my main ewelink account for the app and homebridge with no problems at all!

**Comment by Fannangir** [comment]
Understand your point,
I guess it would be better to provide instant feedback (although you are not sure whether the device  actually changed its state).
Maybe there could be an option to add some polling or wait to the "ok" packet in the background?
If "ok" does not arrive let's say within 3/5/10 seconds (or user defined), revert the device state (or something....)?

**Comment by Fannangir** [comment]
Thanks for the tip regarding multiple accounts.
Generally, I don't mind to keep both, created just for the homebridge usage :).

**Comment by bwp91** [comment]
https://github.com/bwp91/homebridge-ewelink-beta/releases/tag/v2.12.2

Update to the beta plugin - the notes may be of interest!

**Comment by Fannangir** [comment]
Very interesting update.
I have updated, working well.
Is there any option top check whether the device operate via LAN mode or Cloud? Or should I enable LAN mode via ewelink app?

**Comment by bwp91** [comment]
If you look at the logs if you restart homebridge, in the list of sonoff devices will either say “and found locally with IP ...” or “but LAN mode unavailable”.
If it has an IP then it supports LAN mode.
And with the recentl firmware versions for devices that support it, the LAN mode is automatically turned on and it runs along side “cloud” mode

**Comment by Fannangir** [comment]
Got it, I can see "found local IP"
Although I have seen the following added:

[8/1/2020, 3:52:46 PM] [eWeLink] Web socket error - [Error: getaddrinfo ENOTFOUND as-pconnect2.coolkit.cc
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
 {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'as-pconnect2.coolkit.cc'
}].[8/1/2020, 3:52:46 PM] [eWeLink] Web socket closed - [1006].
[8/1/2020, 3:52:46 PM] [eWeLink] Web socket will try to reconnect in five seconds then try the command again.
[8/1/2020, 3:52:46 PM] [eWeLink] If this was unexpected then please try restarting Homebridge.

After showing 3 times the following:

}].[8/1/2020, 3:52:46 PM] [eWeLink] Web socket closed - [1006].
[8/1/2020, 3:52:46 PM] [eWeLink] Web socket will try to reconnect in five seconds then try the command again.
[8/1/2020, 3:52:46 PM] [eWeLink] If this was unexpected then please try restarting Homebridge.

It stopped, although all three switches are working.

**Comment by bwp91** [comment]
Now this one has stumped me.
May I ask which country you reside in? and the country code you use for your ewelink account?

**Comment by Fannangir** [comment]
+972 Israel

**Comment by bwp91** [comment]
Would you be able to go to the settings and turn on "Debug Requests & Responses" (or add `"debugReqRes": true,` to the homebridge config json file)
then restart Homebridge and copy and paste all the "ewelink" lines for me? 
Either reply here or send it to my email bwp91@icloud.com
Sensitive data should be removed **from my plugin** log entries, but feel free to remove the non-sonoff lines of the log.
And then I would advise to turn the "Debug Requests & Responses" setting off again afterwards.
Many thanks
Ben

**Comment by bwp91** [comment]
How does the speed/responsiveness seem in the new update?

**Comment by Fannangir** [comment]
Very fast.
I have tried to control from Home Assistant as well, the update in Homebride and Homekit is instant.
You have done an awesome job.
Thanks 🙏🏻.

**Comment by bwp91** [comment]
Ah great to hear. Thank you!
are you happy for this issue to be closed?

**Comment by Fannangir** [comment]
Sure,
Thanks.
