### ISSUE TITLE
Config is not automatically pulling in "countryCode:"

### ISSUE THREAD

**Issue by bozzy01** [bwp91/homebridge-ewelink-sonoff#18]
When I entered the settings from the plugins page under settings it did not pull the countryCode line into the config. This caused the error below:

> [eWeLink] ** Could not load homebridge-ewelink-sonoff **
[eWeLink] Make sure your eWeLink credentials are in the Homebridge configuration.

After I manually entered the countryCode line in under the password in config it was able to login and automatically added my devices. 

P.S. love that someone finally made a working version for eWeLink , thanks!

**Comment by edgaryau** [comment]
The country code seems being treat as int rather than string currently, need double quote it manually in config.

**Comment by bwp91** [comment]
hey thanks for bringing this up.
this should be corrected in v2.15.2.
the country code will now be treated as a string so it should be automatically double quoted in the config if the plugins > settings is used.

**Comment by bwp91** [comment]
Gonna close this as Im confident all is fixed. Please feel free to reopen if you find the issue still occurs.
Thanks again
