### ISSUE TITLE
Support new zigbee bridge

### ISSUE THREAD

**Issue by tasict** [bwp91/homebridge-ewelink-sonoff#19]
Please support new zbridge  and sensors

**Comment by bwp91** [comment]
Hi,
Since I don’t own this device i would need some extra info from you.
Would you be happy to send me an email?

**Comment by bwp91** [comment]
bwp91@icloud.com

**Comment by tasict** [comment]
Thanks, I will very happy to do this.  Before it i will try to modify your code and do some test.😃

**Comment by bwp91** [comment]
Sure.
First place I would start is in `lib/constants.js` and the line `66: 0, // "ZIGBEE_MAIN_DEVICE"` I assume could be the ZBBridge? Change the `0` to `1` so it gets recognised by the plugin, and then the line `devicesBridge: [28],` I would add the ZBBridge by changing that line to `devicesBridge: [28, 66],`.
Hope this all makes sense!

**Comment by tasict** [comment]
ZBBridge data struct is different than RF Bridge. All sub device has it own device id, and sonoff websocket server will send notify data with sub device id when sub device event happen. It look like below:
{
	"settings": {
		"opsNotify": 0,
		"opsHistory": 1,
		"alarmNotify": 1,
		"wxAlarmNotify": 0,
		"wxOpsNotify": 0,
		"wxDoorbellNotify": 0,
		"appDoorbellNotify": 1
	},
	"family": {
		"id": "5f2d3ae8b0005300087xxxxx",
		"index": 0
	},
	"group": "",
	"online": true,
	"shareUsersInfo": [],
	"groups": [],
	"devGroups": [],
	"_id": "xxxxxxxxx",
	"deviceid": "1000exxxxx",
	"name": "Sonoff_ZBBridge_xxxxx",
	"type": "10",
	"apikey": "xxxxx-xxxx-xxx-xxx-xxxxxx",
	"extra": {
		"extra": {
			"uiid": 66,
			"description": "20200616003",
			"brandId": "5c4c1aee3a7d24c7100be054",
			"apmac": "xx:xxx:xxx:xx:xx",
			"mac": "xx:xx:xx:xx:xx:xx",
			"ui": "Zigbee网关",
			"modelInfo": "5xxxxx",
			"model": "ZBG-AB0-GL",
			"manufacturer": "深圳松诺技术有限公司"
		},
		"_id": "xxxxxxxxxx"
	},
	"createdAt": "2020-08-08T07:24:55.387Z",
	"__v": 0,
	"onlineTime": "2020-08-10T00:36:05.631Z",
	"params": {
		"version": 7,
		"subDevNum": 1,
		"subDevMaxNum": 32,
		"sledOnline": "off",
		"zled": "off",
		"fwVersion": "1.1.0",
		"subDevices": [{
			"subDevId": "xxxxxxxxxxx",
			"deviceid": "xxxxxxxxx",
			"uiid": "1000"
		}],
		"rssi": -62
	},
	"ip": "xxx.xx.xx.xx",
	"location": "台湾",
	"offlineTime": "2020-08-09T12:00:36.881Z",
	"sharedTo": [],
	"devicekey": "xxxx-xxxx-xxx-xxx-ba8fb6bxxxxx",
	"deviceUrl": "",
	"brandName": "SONOFF",
	"showBrand": true,
	"brandLogoUrl": "https://as-ota.coolkit.cc/logo/q62PevoglDNmwUJ9oPE7kRrpt1nL1CoA.png",
	"productModel": " ",
	"devConfig": {},
	"uiid": 66
}

**Comment by bwp91** [comment]
This is very helpful a good place for me to make a start. Could you send me an example web socket log of a “subdevice” when it sends a notification update?

**Comment by tasict** [comment]
I only have two sub device.
* When push the Wireless Button(uiid=3026)
websocket will receive below:
[{"action":"update","deviceid":"xxxxxx77","apikey":"xxxxx-xxxx-xxx-xxxx-xxxxxx","userAgent":"device","d_seq":42766,"ts":0,"params":{"trigTime":"1597071560629","key":0},"from":"device"}]
In my test, I found that "Type" value will different - Click:0 Double Click:1 Long Click:2

*ZigBee Wireless door/window sensor (uiid=3026)
websocket will receive:
[{"action":"update","deviceid":"xxxxx081","apikey":"xxxxx-xxxx-xxx-xxxx-xxxxxx","userAgent":"device","d_seq":59109,"ts":0,"params":{"lock":1,"trigTime":"1597071570727"},"from":"device"}]
which "lock" value 1 is for opened and 0 is closed

**Comment by bwp91** [comment]
Thanks for that.
I will have a think about the best way I can implement this into the plugin. 
I might need your help testing but i’ll keep this issue open and let you know when i have made some progress!

**Comment by tasict** [comment]
Thanks for that and i will very happy to test it. In face i already implement partial code. It just add device to homebridge without update device status to homebridge now. The git repository is 
https://github.com/tasict/homebridge-ewelink-sonoff

**Comment by bwp91** [comment]
Please submit a pull request so I can get this code into the this package.
That's great!

**Comment by bwp91** [comment]
in the subdevices of your first log:
```json
"subDevices": [{
   "subDevId": "xxxxxxxxxxx",
   "deviceid": "xxxxxxxxx",
   "uiid": "1000"
}],
```
What is the difference between the two different device ids? Is this `deviceid` the device id of the bridge itself?

Also, in the second log of a device update through web socket:
```json
{
   "action":"update",
   "deviceid":"xxxxxx77",
   "apikey":"xxxxx-xxxx-xxx-xxxx-xxxxxx",
   "userAgent":"device",
   "d_seq":42766,
   "ts":0,
   "params":{
      "trigTime":"1597071560629",
      "key":0
   },
   "from":"device"
}
```
The `deviceid` that is send here, does this refer to `deviceid` in the first log or the `subDevId`?

**Comment by tasict** [comment]
> The deviceid that is send here, does this refer to deviceid in the first log or the subDevId?
yes

**Comment by bwp91** [comment]
Im still not clear on what `deviceid` refers to?

**Comment by bwp91** [comment]
if you were able to share your bridge with me that would be super helpful :-)

**Comment by tasict** [comment]
Sure, could  you tell me your ewelink account and country code?

**Comment by bwp91** [comment]
> Sure, could you tell me your ewelink account and country code?
Do you know the region of your ewelink account? 
Will be either eu, as, us or cn depending on where in the world you reside!

**Comment by tasict** [comment]
I live in Taiwan which phone country code is +886 and i guess my ewelink acount region is 'us'.
Maybe i  can share device to your ewelink acount by Sonoff App.

**Comment by bwp91** [comment]
Yes but it’s impossible to share devices over different regions which is why my account would need to be in the same region as yours.
You can check which region you are from the Homebridge logs, when the plugin initially loads, there will be a line “API host received: ##-api.coolkit.cc....”
And the ## is either 
eu for europe 
as for asia
us for america
cn for china

please let me know which region you are!

**Comment by bwp91** [comment]
Or, a different method, please try sharing the device with these email addresses and hopefully one will work:
- bwp91@icloud.com (country code 44)
- ben_my@thepotterfamily.uk (country code 60)
- ben_sa@thepotterfamily.uk (country code 55)

**Comment by tasict** [comment]
Done, but only ben_my@thepotterfamily.uk (country code 60) can share success.

**Comment by bwp91** [comment]
Thank you. Got it.
Both sub devices appear offline, is that correct?

**Comment by tasict** [comment]
I am not sure. Sub device's connection is not very stable and i don't know why.

**Comment by bwp91** [comment]
could you send me an email bwp91@icloud.com ?

**Comment by bwp91** [comment]
Support for the ZigBee bridge has been added in v2.19.0.
For this reason I will close this issue.
If anyone experiences issues then please feel free to reopen this issue or create a new one.
Thanks
Ben
