### ISSUE TITLE
Support Sonoff RF Bridge buttons

### ISSUE THREAD

**Issue by pfandrade** [bwp91/homebridge-ewelink-sonoff#20]
**Please explain your feature request in one sentence.**
Besides sensors, the Sonoff RF Bridge can also simulate 433 RF signals (your typical garage remote button). It would be cool to support this as well.

**Is your feature request related to a problem? Please describe.**
No.

**Any particular Sonoff devices that this relates to?**
Sonoff RF Bridge

**Anything else?**
Nice work!

**Comment by bwp91** [comment]
Hiya,
Yes this is something I know I haven't implemented... yet. I don't own the RF Bridge so I've been relying on other users to implement what I have so far.
Would you be prepared to share your RF Bridge with my ewelink account so I can have a look at the data structures etc? I assume you have buttons linked to your rf bridge?

**Comment by pfandrade** [comment]
Yes I do have buttons there (only button actually).

I've been looking at the code, maybe I can file a PR to add support for that. If I encounter any issues I'll ask for your help. And we can always fallback to giving you access to the bridge if I'm not able to get it working.

**Comment by bwp91** [comment]
https://github.com/AlexxIT/SonoffLAN/blob/master/custom_components/sonoff/remote.py

This could be helpful.

**Comment by bwp91** [comment]
A PR would be amazing if you're able to, even for a starting point for me. 
Adding support for devices I don't have myself can be challenging sometimes!

**Comment by bwp91** [comment]
What were you thought on how to actually implement a button in homekit?

**Comment by pfandrade** [comment]
I actually don't know yet. I've only just started with HomeBridge and HomeKit. Looking at other homebridge plugins looks like I'd have to model it as a switch. My guess would be to code it as a switch that will automatically turn off so it behaves more like a button.

Anyway, I've encountered a hurdle yesterday (unrelated) that I don't know how to fix yet. Apparently the the Sonos RF Bridge only works with 24bit RF signals… but the garage door motor is using 28bit. It learnt the buttons on my remote just fine, but they can't actually open the door.

**Comment by bhofer-tal** [comment]
Would be also interrested in this feature, because we use the RF bridge just as a remote for several devices like the canvas for our projector, several blinds and the garage door. Not as a sensor. I played around a little bit trying to set it up as a new group type, but I am just a beginner and can‘t figure ist out yet. Thanks guys!

**Comment by bwp91** [comment]
The most straightforward way for me to implement a new device is for me to have access to it - by someone giving me shared access through their ewelink account.
Which is pretty "safe" when its for example a light or a fan.
But I feel weird asking for access to someone's device especially when it could be linked to garage doors. So I can understand the hesitation.

But if there is someone who has buttons linked to and RF Bridge, and are willing to share their bridge with me this would help me out a lot with regards to implementation.

**Comment by bhofer-tal** [comment]
Thanks for your message. I totally understand and for me it's no problem to share the RF bridge device in my ewelink account with you - if it helps to develop this additional feature! Please just send me your ewelink account e-mail so I can add you. Thanks!

**Comment by bwp91** [comment]
@bhofer-tal which country do you live in?

**Comment by bhofer-tal** [comment]
Austria (country code: 43)

**Comment by bwp91** [comment]
Okay please share with bwp91@icloud.com

**Comment by bhofer-tal** [comment]
Perfect, thanks. I will share the device with you in a couple of hours, when I am back home...

**Comment by pfandrade** [comment]
Hey @bwp91 let me know if you need another device, I'm still messing with mine but I can leave it on for a week or so with a few buttons configured (that actually don't do anything) so you can play with it.

**Comment by bwp91** [comment]
> Hey @bwp91 let me know if you need another device, I'm still messing with mine but I can leave it on for a week or so with a few buttons configured (that actually don't do anything) so you can play with it.

The more devices I have to test with the better. If you're in europe then please share to the same email address as above!

**Comment by bhofer-tal** [comment]
hey @bwp91 what is your Country Code? So I can share the device with you?

**Comment by bwp91** [comment]
@bhofer-tal +44

Also please send me a separate email with a tiny explanation of connected devices and which ones I can play with!

**Comment by bwp91** [comment]
> hey @bwp91 what is your Country Code? So I can share the device with you?

got it!
please send me an email so i can get back to you

**Comment by bhofer-tal** [comment]
> please send me an email so i can get back to you

perfect. email is already on it‘s way to you!

**Comment by bwp91** [comment]
Just an update

It looks like I have been successful in implementing the buttons!

Now needs a bit of testing.

**Comment by bwp91** [comment]
@pfandrade if you're interesting in testing this then let me know and i can give you more info. i'm pretty much finished!

**Comment by bwp91** [comment]
Support for the RF Bridge buttons has been added in v2.19.0.
For this reason I will close this issue.
To change current accessories from the default "motion sensor" to a button, please use the settings page for the plugin in homebridge, and restart homebridge.
I will update the wiki when I have some free time.
If anyone experiences issues then please feel free to reopen this issue or create a new one.
Thanks
Ben

**Comment by bhofer-tal** [comment]
Thanks again for adding this feature and your support - it works just fine and finally I can use the RF bridge as supposed within the Home app.
