### ISSUE TITLE
Siri commands dont work

### ISSUE THREAD

**Issue by s1rbruce** [bwp91/homebridge-ewelink-sonoff#23]
Hello,

When I say for expample turn on desk, the siri dont know what I said, when I tried on different plugin (max) it works, is there any command difference? 

I have latest version of plugin. Thanks for response!

**Comment by bwp91** [comment]
Hi @s1rbruce 
There shouldn't be any difference with Siri commands to control the HomeKit accessories.
You can use the Home app to rename accessories and assign rooms which help's Siri understand what you are trying to do.
Are you having trouble with one accessory in particular or many accessories?

**Comment by s1rbruce** [comment]
It looks like on problem with ios 14
On my iPad it works really fine. Yes all accessories with this plugin. So I have to wait.

**Comment by bwp91** [comment]
Ah good to hear it works well on your ipad.
As the ios14 aspect is totally out of my control are you happy for this issue to be closed?
Thanks
Ben

**Comment by s1rbruce** [comment]
Absolutely, I found some things on reddit which saying there is bug in ios14. 

So can be closed, thanks a lot for your work.

**Comment by bwp91** [comment]
Very welcome.
