### ISSUE TITLE
Not an issue, just a pointer to a PR of interest

### ISSUE THREAD

**Issue by dhutchison** [bwp91/homebridge-ewelink-sonoff#4]
No idea how much you diverged from the original homebridge-ewelink codebase by now, but I just submitted a pretty big PR which probably overlaps with at least some of what you have been doing too (remove the duplication, abstract out API parts). 

May be of interest to you to take a look: https://github.com/howanghk/homebridge-ewelink/pull/114/

Hopefully it gets merged, if not... keen not to be creating yet another competing plugin. Just need to wait and see.

**Comment by thepotterfamily** [comment]
I will have a good look into what you have done - but it seems you have been working hard!
My main aims so far have been:
- rewrite the code in a way that I find easier to maintain
- support for more devices
I have the view that eventually it would nice to integrate everything together and even get it merged down to the original homebridge-ewelink package. Just at the moment I'm making so many constant changes that either I would be making a number of pull requests every day!
