### ISSUE TITLE
"due to missing type parameter"

### ISSUE THREAD

**Issue by imtitanic** [bwp91/homebridge-ewelink-sonoff#7]
**What issue do you have?**
I don't know if this is a issue or my fault, but on the homebridge's log appears a message constantly for the ewelink devices

**Which version of the package are you using?**
 v2.4.0

**Please paste any relevant logs below**
[2020-7-14 11:25:29] [eWeLink] [Luz de Entrada ] will not be refreshed due to missing type parameter.
Please remove [Luz de Entrada ] from the Homebridge cache (including any secondary devices (SW1, SW2, etc.).
[2020-7-14 11:25:47] [eWeLink] [Luz de Entrada ] will not be refreshed due to missing type parameter.
Please remove [Luz de Entrada ] from the Homebridge cache (including any secondary devices (SW1, SW2, etc.).
[2020-7-14 11:25:47] [eWeLink] [Puerta Eléctrica] will not be refreshed due to missing type parameter.
Please remove [Puerta Eléctrica] from the Homebridge cache (including any secondary devices (SW1, SW2, etc.).
[2020-7-14 11:25:47] [eWeLink] [Interruptor] will not be refreshed due to missing type parameter.
Please remove [Interruptor] from the Homebridge cache (including any secondary devices (SW1, SW2, etc.).
[2020-7-14 11:35:21] [eWeLink] [Luz de Entrada ] has been reported [online].
[2020-7-14 11:35:21] [eWeLink] [Luz de Entrada ] will not be refreshed due to missing type parameter.
Please remove [Luz de Entrada ] from the Homebridge cache (including any secondary devices (SW1, SW2, etc.).
[2020-7-14 12:11:27] [eWeLink] [Luz de Entrada ] has been reported [online].
[2020-7-14 12:11:28] [eWeLink] [Luz de Entrada ] will not be refreshed due to missing type parameter.
Please remove [Luz de Entrada ] from the Homebridge cache (including any secondary devices (SW1, SW2, etc.).

**Comment by bwp91** [comment]
Hi,
Have you tried removing devices from the cache?
Please try removing one device at a time for example "Luz de Entrada" and then restart Homebridge.
If it works then do the same for "Puerta Eléctrica" and "Interruptor".
If this doesn't work then let me know and I'll try and see what's going on.
Thanks
Ben

**Comment by bwp91** [comment]
Just a quick question, even though these messages are appearing in the log, are the devices working as you'd expect through Homebridge/Home app?

**Comment by bwp91** [comment]
I may have found the issue. Please upgrade to v2.5.3 and let me know if you still get the messages.
Ben

**Comment by imtitanic** [comment]
I did the cache thing, but appears again but yes I can use the devices normally, sometimes the home app shows the messange "no response" but restarting homebridge solves that, so it's homebridge problem.

And okay! I will update and tell you whats happen.

**Comment by bwp91** [comment]
> sometimes the home app shows the messange "no response" but restarting homebridge solves that, so it's homebridge problem.

Could very well be an issue I have in the code. Keep an eye on this, and perhaps set "debug" to true in the config (and then restart Homebridge) as this shows more logs and an error message might come up which would be the reason for "no response".

**Comment by bwp91** [comment]
@imtitanic are you still experiencing "No response" errors?
If all seems okay then are you happy for me to close this issue?
Thanks

**Comment by imtitanic** [comment]
hey there!

48 hours left and nothing about the message, so everything is ok. Thanks!
